{{- if REPLACE_CRD_EXPRESSION }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: "REPLACE_CRD_NAME"
  {{- if .Values.crds.keep }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
  labels:
    {{- include "REPLACE_LABELS_TEMPLATE" . | nindent 4 }}
