example_location: "examples"
api_groups:
  - "Certmanager"
  - "ACME"
resource_categories:
- name: "Certmanager"
  include: "certmanager"
  resources:
  - name: "Certificate"
    version: "v1alpha2"
    group: "certmanager"
  - name: "ClusterIssuer"
    version: "v1alpha2"
    group: "certmanager"
  - name: "Issuer"
    version: "v1alpha2"
    group: "certmanager"
- name: "ACME"
  include: "acme"
  resources:
    - name: "Order"
      version: "v1alpha2"
      group: "acme"
    - name: "Challenge"
      version: "v1alpha2"
      group: "acme"
