apiVersion: v1
kind: ConfigMap
metadata:
  name: route-place-holder-config
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.json: |
    {
    }
