# Copyright 2020 The Jetstack cert-manager contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM quay.io/jetstack/cert-manager-controller:v0.15.0-alpha.0 as source
FROM registry.access.redhat.com/ubi8/ubi-minimal

COPY --from=source /app /app
# Required Licenses
ADD https://raw.githubusercontent.com/jetstack/cert-manager/v0.15.0-alpha.0/LICENSE /licenses/LICENSE
ADD https://raw.githubusercontent.com/jetstack/cert-manager/v0.15.0-alpha.0/LICENSES /licenses/LICENSES

### Required OpenShift Labels
LABEL name="cert-manager controller" \
      vendor="Jetstack" \
      version="v0.15.0-alpha.1" \
      release="1" \
      summary="This is the cert-manager controller image." \
      description="This image contains the main cert-manager controller."

CMD "/app/cmd/controller/controller"