---
apiVersion: v1
kind: Service
metadata:
  name: bind
  labels:
    name: bind
spec:
  type: ClusterIP
  # hardcoded to make this service easily accessible via IP only
  clusterIP: {SERVICE_IP_PREFIX}.16
  ports:
  - port: 53
    targetPort: 53
    protocol: UDP
  selector:
    app: bind
