/*
Copyright 2026 The cert-manager Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package admission

import (
	"errors"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ErrResourceUnset is returned by plugins that gate on AdmissionRequest.Resource
// when that field is the zero value.
//
// A real kube-apiserver always populates Resource, so this should only trip
// for hand-crafted AdmissionReviews, e.g. one POSTed directly to the webhook
// endpoint, or generated by a non-conformant aggregated/virtual apiserver.
//
// Plugins must check IsResourceUnset and return this error instead of falling
// through to their usual "this isn't the resource I care about, skip" gate: a
// zero-valued Resource never matches any plugin's gate, so silently skipping
// would let the request through Allowed rather than denying it.
var ErrResourceUnset = errors.New("internal error: admission request Resource field is unset")

// IsResourceUnset reports whether gvr is the zero value.
func IsResourceUnset(gvr metav1.GroupVersionResource) bool {
	return gvr == metav1.GroupVersionResource{}
}
