apiVersion: v1
kind: Namespace
metadata:
  name: haproxy-ingress
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-ingress-config
  namespace: haproxy-ingress
data:
  max-connections: "250"
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GatewayClass
metadata:
  name: haproxy-acmesolver
spec:
  controllerName: haproxy-ingress.github.io/controller
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1alpha2
metadata:
  name: acmesolver
  namespace: haproxy-ingress
spec:
  gatewayClassName: haproxy-acmesolver
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
