apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v01.api.letsencrypt.org/directory
    email: {{ .Values.letsencrypt.email }}
    privateKeySecretRef:
      name: letsencrypt-production-cluster-key-pair
    http01: {}
