//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The cert-manager Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ACMEDNS01Config) DeepCopyInto(out *ACMEDNS01Config) {
	*out = *in
	if in.RecursiveNameservers != nil {
		in, out := &in.RecursiveNameservers, &out.RecursiveNameservers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RecursiveNameserversOnly != nil {
		in, out := &in.RecursiveNameserversOnly, &out.RecursiveNameserversOnly
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ACMEDNS01Config.
func (in *ACMEDNS01Config) DeepCopy() *ACMEDNS01Config {
	if in == nil {
		return nil
	}
	out := new(ACMEDNS01Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ACMEHTTP01Config) DeepCopyInto(out *ACMEHTTP01Config) {
	*out = *in
	if in.SolverRunAsNonRoot != nil {
		in, out := &in.SolverRunAsNonRoot, &out.SolverRunAsNonRoot
		*out = new(bool)
		**out = **in
	}
	if in.SolverNameservers != nil {
		in, out := &in.SolverNameservers, &out.SolverNameservers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ACMEHTTP01Config.
func (in *ACMEHTTP01Config) DeepCopy() *ACMEHTTP01Config {
	if in == nil {
		return nil
	}
	out := new(ACMEHTTP01Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfiguration) DeepCopyInto(out *ControllerConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.KubernetesAPIQPS != nil {
		in, out := &in.KubernetesAPIQPS, &out.KubernetesAPIQPS
		*out = new(float32)
		**out = **in
	}
	if in.KubernetesAPIBurst != nil {
		in, out := &in.KubernetesAPIBurst, &out.KubernetesAPIBurst
		*out = new(int32)
		**out = **in
	}
	in.LeaderElectionConfig.DeepCopyInto(&out.LeaderElectionConfig)
	if in.Controllers != nil {
		in, out := &in.Controllers, &out.Controllers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IssuerAmbientCredentials != nil {
		in, out := &in.IssuerAmbientCredentials, &out.IssuerAmbientCredentials
		*out = new(bool)
		**out = **in
	}
	if in.ClusterIssuerAmbientCredentials != nil {
		in, out := &in.ClusterIssuerAmbientCredentials, &out.ClusterIssuerAmbientCredentials
		*out = new(bool)
		**out = **in
	}
	if in.EnableCertificateOwnerRef != nil {
		in, out := &in.EnableCertificateOwnerRef, &out.EnableCertificateOwnerRef
		*out = new(bool)
		**out = **in
	}
	if in.CopiedAnnotationPrefixes != nil {
		in, out := &in.CopiedAnnotationPrefixes, &out.CopiedAnnotationPrefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NumberOfConcurrentWorkers != nil {
		in, out := &in.NumberOfConcurrentWorkers, &out.NumberOfConcurrentWorkers
		*out = new(int32)
		**out = **in
	}
	if in.MaxConcurrentChallenges != nil {
		in, out := &in.MaxConcurrentChallenges, &out.MaxConcurrentChallenges
		*out = new(int32)
		**out = **in
	}
	in.MetricsTLSConfig.DeepCopyInto(&out.MetricsTLSConfig)
	if in.EnablePprof != nil {
		in, out := &in.EnablePprof, &out.EnablePprof
		*out = new(bool)
		**out = **in
	}
	in.Logging.DeepCopyInto(&out.Logging)
	if in.FeatureGates != nil {
		in, out := &in.FeatureGates, &out.FeatureGates
		*out = make(map[string]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.IngressShimConfig.DeepCopyInto(&out.IngressShimConfig)
	in.ACMEHTTP01Config.DeepCopyInto(&out.ACMEHTTP01Config)
	in.ACMEDNS01Config.DeepCopyInto(&out.ACMEDNS01Config)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfiguration.
func (in *ControllerConfiguration) DeepCopy() *ControllerConfiguration {
	if in == nil {
		return nil
	}
	out := new(ControllerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControllerConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicServingConfig) DeepCopyInto(out *DynamicServingConfig) {
	*out = *in
	if in.DNSNames != nil {
		in, out := &in.DNSNames, &out.DNSNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicServingConfig.
func (in *DynamicServingConfig) DeepCopy() *DynamicServingConfig {
	if in == nil {
		return nil
	}
	out := new(DynamicServingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilesystemServingConfig) DeepCopyInto(out *FilesystemServingConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilesystemServingConfig.
func (in *FilesystemServingConfig) DeepCopy() *FilesystemServingConfig {
	if in == nil {
		return nil
	}
	out := new(FilesystemServingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressShimConfig) DeepCopyInto(out *IngressShimConfig) {
	*out = *in
	if in.DefaultAutoCertificateAnnotations != nil {
		in, out := &in.DefaultAutoCertificateAnnotations, &out.DefaultAutoCertificateAnnotations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressShimConfig.
func (in *IngressShimConfig) DeepCopy() *IngressShimConfig {
	if in == nil {
		return nil
	}
	out := new(IngressShimConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeConfig) DeepCopyInto(out *KubeConfig) {
	*out = *in
	if in.CurrentContext != nil {
		in, out := &in.CurrentContext, &out.CurrentContext
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeConfig.
func (in *KubeConfig) DeepCopy() *KubeConfig {
	if in == nil {
		return nil
	}
	out := new(KubeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeaderElectionConfig) DeepCopyInto(out *LeaderElectionConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeaderElectionConfig.
func (in *LeaderElectionConfig) DeepCopy() *LeaderElectionConfig {
	if in == nil {
		return nil
	}
	out := new(LeaderElectionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
	if in.CipherSuites != nil {
		in, out := &in.CipherSuites, &out.CipherSuites
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Filesystem = in.Filesystem
	in.Dynamic.DeepCopyInto(&out.Dynamic)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}
