apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager-operator
  template:
    metadata:
      labels:
        app: cert-manager-operator
    spec:
      serviceAccountName: cert-manager-operator
      containers:
        - name: cert-manager-operator
          # Replace this with the built image name
          image: bazel/deploy/olm:helm-operator
          imagePullPolicy: Never
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cert-manager-operator"
