{{- if .Values.cainjector.podDisruptionBudget -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "cainjector.fullname" . }}-pdb
  namespace: {{ .Release.Namespace }}
  labels: 
    app: {{ include "cert-manager.name" . }}
    app.kubernetes.io/name: {{ include "cert-manager.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "controller"
    {{- include "labels" . | nindent 4 }}
spec:
  {{ toYaml .Values.podDisruptionBudget }}
  selector:
    matchLabels:
      app: cainjector
      app.kubernetes.io/component: cainjector
      app.kubernetes.io/instance: certmanager
{{- end -}}
