{{- if .Values.createCustomResource -}}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: orders.certmanager.k8s.io
  labels:
    app.kubernetes.io/name: {{ template "cert-manager.name" . }}
    app.kubernetes.io/part-of: {{ template "cert-manager.name" . }}
    app: {{ template "cert-manager.name" . }}
    release: {{ .Release.Name }}
    chart: {{ template "cert-manager.chart" . }}
    heritage: {{ .Release.Service }}
spec:
  group: certmanager.k8s.io
  version: v1alpha1
  names:
    kind: Order
    plural: orders
  scope: Namespaced
{{- end -}}
