{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cert-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ template "cert-manager.name" . }}
    app.kubernetes.io/part-of: {{ template "cert-manager.name" . }}
    app: {{ template "cert-manager.name" . }}
    release: {{ .Release.Name }}
    chart: {{ template "cert-manager.chart" . }}
    heritage: {{ .Release.Service }}
{{- end -}}
