replicaCount: 1

strategy: {}
  # type: RollingUpdate
  # rollingUpdate:
  #   maxSurge: 0
  #   maxUnavailable: 1

podAnnotations: {}

# Optional additional arguments for webhook
extraArgs: []

resources: {}
  # requests:
  #   cpu: 10m
  #   memory: 32Mi

image:
  repository: quay.io/jetstack/cert-manager-webhook
  tag: canary
  pullPolicy: Always

caSyncImage:
  repository: quay.io/munnerz/apiextensions-ca-helper
  tag: v0.1.0
  pullPolicy: IfNotPresent
