replicaCount: 1

podAnnotations: {}

# Optional additional arguments for webhook
extraArgs: []

resources: {}
  # requests:
  #   cpu: 10m
  #   memory: 32Mi

image:
  repository: quay.io/jetstack/cert-manager-webhook
  tag: v0.6.0-alpha.0
  pullPolicy: IfNotPresent

caSyncImage:
  repository: quay.io/munnerz/apiextensions-ca-helper
  tag: v0.1.0
  pullPolicy: IfNotPresent
