# Copyright 2024 The cert-manager Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is auto-generated by the learn_kind_images.sh script in the makefile-modules repo.
# Do not edit manually.

kind_image_kindversion := v0.29.0

kind_image_kube_1.30_amd64 := docker.io/kindest/node:v1.30.13@sha256:cf819926d6f5ba996f7489fa18a38156f952f5dd172395da7d83f734190e95da
kind_image_kube_1.30_arm64 := docker.io/kindest/node:v1.30.13@sha256:80a284ddc8886bc12ede5ecb1e65f7a927ca15847e6a0e958e01bf903222fe87
kind_image_kube_1.31_amd64 := docker.io/kindest/node:v1.31.9@sha256:48608b82ab1a6a97f735d621451525affab9c8dc91dcc2cab80ee0efcbd216da
kind_image_kube_1.31_arm64 := docker.io/kindest/node:v1.31.9@sha256:ccbba29cfd3e42e4b5102426c1bf1486643a0eb461ea9617526f819c95151406
kind_image_kube_1.32_amd64 := docker.io/kindest/node:v1.32.5@sha256:5d5a4d793d2a3d9727013b8b0cf6c95008c71abeb547759a273ef27e9c564984
kind_image_kube_1.32_arm64 := docker.io/kindest/node:v1.32.5@sha256:0fddc6deec2a667040504053eccb8ecaa0fb2fb5e5e7f6a2e0f60294667b7412
kind_image_kube_1.33_amd64 := docker.io/kindest/node:v1.33.1@sha256:14ffd6ee8a3daa20cc934ba786626b181e1797268c5465f2c299a7cf54494c77
kind_image_kube_1.33_arm64 := docker.io/kindest/node:v1.33.1@sha256:cfea27c21c338b9948ea55c413b9c9e2549f3df89a89424889a1fd3ecb0c8951

kind_image_latest_amd64 := $(kind_image_kube_1.33_amd64)
kind_image_latest_arm64 := $(kind_image_kube_1.33_arm64)
