ARG BASE_IMAGE

FROM $BASE_IMAGE

USER 1000

COPY controller /app/cmd/controller/controller
COPY cert-manager.license /licenses/LICENSE
COPY cert-manager.licenses_notice /licenses/LICENSES

ENTRYPOINT ["/app/cmd/controller/controller"]

# vim: syntax=dockerfile
