ARG BASE_IMAGE

FROM $BASE_IMAGE

USER 1000

COPY acmesolver /app/cmd/acmesolver/acmesolver
COPY cert-manager.license /licenses/LICENSE
COPY cert-manager.licenses_notice /licenses/LICENSES

ENTRYPOINT ["/app/cmd/acmesolver/acmesolver"]

# vim: syntax=dockerfile
