ARG BASE_IMAGE

FROM $BASE_IMAGE

USER 1000

COPY webhook /app/cmd/webhook/webhook
COPY cert-manager.license /licenses/LICENSE
COPY cert-manager.licenses_notice /licenses/LICENSES

ENTRYPOINT ["/app/cmd/webhook/webhook"]

# vim: syntax=dockerfile
