ARG BASE_IMAGE

FROM $BASE_IMAGE

USER 1000

COPY cainjector /app/cmd/cainjector/cainjector
COPY cert-manager.license /licenses/LICENSE
COPY cert-manager.licenses_notice /licenses/LICENSES

ENTRYPOINT ["/app/cmd/cainjector/cainjector"]

# vim: syntax=dockerfile
