# Copyright 2022 The cert-manager Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by ./hack/latest-kind-images.sh

KIND_IMAGE_K8S_120=docker.io/kindest/node@sha256:a32bf55309294120616886b5338f95dd98a2f7231519c7dedcec32ba29699394
KIND_IMAGE_K8S_121=docker.io/kindest/node@sha256:27ef72ea623ee879a25fe6f9982690a3e370c68286f4356bf643467c552a3888
KIND_IMAGE_K8S_122=docker.io/kindest/node@sha256:c8a828709a53c25cbdc0790c8afe12f25538617c7be879083248981945c38693
KIND_IMAGE_K8S_123=docker.io/kindest/node@sha256:e5fd1d9cd7a9a50939f9c005684df5a6d145e8d695e78463637b79464292e66c
KIND_IMAGE_K8S_124=docker.io/kindest/node@sha256:1e12918b8bc3d4253bc08f640a231bb0d3b2c5a9b28aa3f2ca1aee93e1e8db16
KIND_IMAGE_K8S_125=docker.io/kindest/node@sha256:00d3f5314cc35327706776e95b2f8e504198ce59ac545d0200a89e69fce10b7f

# Manually set - see hack/latest-kind-images.sh for details
KIND_IMAGE_K8S_126=docker.io/kindest/node@sha256:691e24bd2417609db7e589e1a479b902d2e209892a10ce375fab60a8407c7352

# Manually set- see hack/latest-kind-images.sh for details
KIND_IMAGE_K8S_127=docker.io/kindest/node@sha256:9915f5629ef4d29f35b478e819249e89cfaffcbfeebda4324e5c01d53d937b09

# docker.io/kindest/node:v1.20.15
KIND_IMAGE_SHA_K8S_120=sha256:a32bf55309294120616886b5338f95dd98a2f7231519c7dedcec32ba29699394

# docker.io/kindest/node:v1.21.14
KIND_IMAGE_SHA_K8S_121=sha256:27ef72ea623ee879a25fe6f9982690a3e370c68286f4356bf643467c552a3888

# docker.io/kindest/node:v1.22.17
KIND_IMAGE_SHA_K8S_122=sha256:c8a828709a53c25cbdc0790c8afe12f25538617c7be879083248981945c38693

# docker.io/kindest/node:v1.23.17
KIND_IMAGE_SHA_K8S_123=sha256:e5fd1d9cd7a9a50939f9c005684df5a6d145e8d695e78463637b79464292e66c

# docker.io/kindest/node:v1.24.12
KIND_IMAGE_SHA_K8S_124=sha256:1e12918b8bc3d4253bc08f640a231bb0d3b2c5a9b28aa3f2ca1aee93e1e8db16

# docker.io/kindest/node:v1.25.8
KIND_IMAGE_SHA_K8S_125=sha256:00d3f5314cc35327706776e95b2f8e504198ce59ac545d0200a89e69fce10b7f

# Manually set - see hack/latest-kind-images.sh for details
# docker.io/kindest/node:v1.26.0
KIND_IMAGE_SHA_K8S_126=sha256:691e24bd2417609db7e589e1a479b902d2e209892a10ce375fab60a8407c7352

# Manually set - see hack/latest-kind-images.sh for details
# docker.io/kindest/node:v1.27.1
KIND_IMAGE_SHA_K8S_127=sha256:9915f5629ef4d29f35b478e819249e89cfaffcbfeebda4324e5c01d53d937b09

# note that these 'full' digests should be avoided since not all tools support them
# prefer KIND_IMAGE_K8S_*** instead
KIND_IMAGE_FULL_K8S_120=docker.io/kindest/node:v1.20.15@sha256:a32bf55309294120616886b5338f95dd98a2f7231519c7dedcec32ba29699394
KIND_IMAGE_FULL_K8S_121=docker.io/kindest/node:v1.21.14@sha256:27ef72ea623ee879a25fe6f9982690a3e370c68286f4356bf643467c552a3888
KIND_IMAGE_FULL_K8S_122=docker.io/kindest/node:v1.22.17@sha256:c8a828709a53c25cbdc0790c8afe12f25538617c7be879083248981945c38693
KIND_IMAGE_FULL_K8S_123=docker.io/kindest/node:v1.23.17@sha256:e5fd1d9cd7a9a50939f9c005684df5a6d145e8d695e78463637b79464292e66c
KIND_IMAGE_FULL_K8S_124=docker.io/kindest/node:v1.24.12@sha256:1e12918b8bc3d4253bc08f640a231bb0d3b2c5a9b28aa3f2ca1aee93e1e8db16
KIND_IMAGE_FULL_K8S_125=docker.io/kindest/node:v1.25.8@sha256:00d3f5314cc35327706776e95b2f8e504198ce59ac545d0200a89e69fce10b7f

# Manually set - see hack/latest-kind-images.sh for details
KIND_IMAGE_FULL_K8S_126=docker.io/kindest/node:v1.26.0@sha256:691e24bd2417609db7e589e1a479b902d2e209892a10ce375fab60a8407c7352

KIND_IMAGE_FULL_K8S_127=docker.io/kindest/node:v1.27.1@sha256:9915f5629ef4d29f35b478e819249e89cfaffcbfeebda4324e5c01d53d937b09

