apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: user@example.com
    # Name of a secret used to store the ACME account private key
    privateKey: letsncrypt-staging
    # ACME dns-01 provider configurations
    dns-01:
      # Here we define a list of DNS-01 providers that can solve DNS challenges
      providers:
      # We define a provider named 'clouddns', with configuration for the
      # clouddns challenge provider.
      - name: clouddns
        clouddns:
          # A secretKeyRef to a the google cloud json service account
          serviceAccount:
            name: clouddns-service-account
            key: service-account.json
          # The project in which to update the DNS zone
          project: gcloud-project
      # We define a provider named 'cloudflare', with configuration for the
      # cloudflare challenge provider.
      - name: cloudflare
        cloudflare:
          # A secretKeyRef to a the cloudflare api key
          apiKey:
            name: cloudflare-config
            key: api-key
          # The cloudflare user account email
          email: cloudflare-user@example.com
      # We define a provider named 'route53', with configuration for the
      # route53 challenge provider.
      - name: route53
        route53:
          # A secretKeyRef to a the route53 access key ID
          accessKeyID:
            name: route53-config
            key: access-key-id
          # A secretKeyRef to a the route53 secret access key
          secretAccessKey:
            name: route53-config
            key: secret-access-key
          # A secretKeyRef to a the route53 hosted zone ID
          hostedZoneID:
            name: route53-config
            key: hosted-zone-id
          # The route53 region
          region: us-east-1
