apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: http://acme-staging-v02.api.letsencrypt.org/directory
    email: james+test@jetstack.io
    privateKeySecretRef:
      name: le-staging
    dns01:
      providers:
      - name: cloudflare-james
        webhook:
          groupName: solvers.acme.cert-manager.io
          solverName: cloudflare
          config:
            email: james@munnelly.eu
            apiKeySecretRef:
              name: cloudflare-api-key
              key: api-token
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: testcrt
spec:
  secretName: testcrt-tls
  issuerRef:
    name: letsencrypt-staging
  dnsNames:
    - test.k8s.co
  acme:
    config:
      - domains:
          - test.k8s.co
        dns01:
          provider: cloudflare-james
